# Home Assistant add-on: LibreCoach
name: "LibreCoach"
version: "1.2.3"
slug: "librecoach"
description: "Smart home control for your RV"
url: "https://librecoach.com"
maintainer: "Ted Lanham <Backroads4Me@gmail.com>"
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: auto
init: false
hassio_api: true
hassio_role: manager
homeassistant_api: true
privileged:
  - NET_ADMIN
  - NET_RAW
host_network: true
devices:
  - /dev/bus/usb
uart: true
map:
  - share:rw
  - config:rw
options:
  geo_enabled: false
  geo_device_tracker_primary: ""
  geo_device_tracker_secondary: ""
  geo_update_threshold: 10
  microair_enabled: false
  microair_email: ""
  microair_password: ""
  victron_enabled: true
  beta_enabled: false
  confirm_nodered_takeover: false
  prevent_flow_updates: false
  debug_logging: false
  mqtt_user: "librecoach"
  mqtt_pass: "One23four"
  can_interface: "can0"
schema:
  geo_enabled: bool
  geo_device_tracker_primary: str?
  geo_device_tracker_secondary: str?
  geo_update_threshold: "int(1,500)?"
  microair_enabled: bool
  microair_email: str?
  microair_password: password?
  victron_enabled: bool
  beta_enabled: bool
  confirm_nodered_takeover: bool
  prevent_flow_updates: bool
  debug_logging: bool
  mqtt_user: str
  mqtt_pass: password
  can_interface: str
image: ghcr.io/backroads4me/{arch}-librecoach
